// <auto-generated />
using EmartMvcCaseStudy.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmartMvcCaseStudy.Migrations.SubCategory
{
    [DbContext(typeof(SubCategoryContext))]
    [Migration("20200129122427_SubCategoryCreate")]
    partial class SubCategoryCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmartMvcCaseStudy.Models.SubCategory", b =>
                {
                    b.Property<int>("SID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ABOUTSUBCATEGORY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<int>("GST")
                        .HasColumnType("int");

                    b.Property<string>("SNAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SID");

                    b.ToTable("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
