// <auto-generated />
using EmartMvcCaseStudy.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmartMvcCaseStudy.Migrations
{
    [DbContext(typeof(SellerContext))]
    [Migration("20200201091732_SellerCreate")]
    partial class SellerCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmartMvcCaseStudy.Models.Seller", b =>
                {
                    b.Property<int>("SID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOMPANYNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEMAILID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SGSTIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SMOBILENO")
                        .HasColumnType("float");

                    b.Property<string>("SPASSWORD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUSERNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SWEBSITE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SID");

                    b.ToTable("Sellers");
                });
#pragma warning restore 612, 618
        }
    }
}
